b:
	cd my.op/DeSimilarDocs/; javac -cp /opt/ibm/InfoSphereStreams/lib/com.ibm.streams.operator.jar:/opt/ibm/InfoSphereStreams/ext/lib/commons-math-2.1.jar DeSimilarDocs.java; cd ../..
	sc -T -M NewsAggregator

r:
	./output/bin/standalone