application: 532-corp
version: python
runtime: python27
api_version: 1
threadsafe: yes

handlers:

- url: /wp-content
  static_dir: wp-content

- url: .*
  script: main.app

libraries:
- name: webapp2
  version: "2.5.1"
