# Brian Reber (breber@iastate.edu)
# CprE 315X, Spring 2012
# Spell Check Programming Assignment

all: spell-check

spell-check: spell-check.cpp spell-check.h
	g++ -o spell-check spell-check.cpp

clean:
	rm spell-check
	rm *.o
